### ISSUE TITLE
Group option

### ISSUE THREAD

**Issue by FallenLeave91** [Devqon/lovelace-mini-thermostat#10]
First of all great card! Could there be an option for it to look better in a group of entities? The mini-media-player card has an option for this, so it doesn´t show the border of the card.

**Comment by Devqon** [comment]
Added in v0.1.0

**Comment by FallenLeave91** [comment]
After updating and adding the grouped option it still looks the same. Am I doin something wrong here?

```
  - type: 'custom:mini-thermostat'
    entity: climate.heizung_wohnzimmer
    grouped: true
    layout:
      dropdown: preset_modes
```
