### ISSUE TITLE
Smaller title/name size adjustments

### ISSUE THREAD

**Issue by artkrz** [Devqon/lovelace-mini-thermostat#11]
Grate card. Could you add an option to adjust size of the title? I want to stack multiple cards and it takes a lot of space even now when I have 2 thermostats.

![obraz](https://user-images.githubusercontent.com/209375/73522129-fe4adb80-4407-11ea-976d-f777f2524499.png)

**Comment by Devqon** [comment]
There are several ways to fix this, and you can already take full control already with the [card mod](https://github.com/thomasloven/lovelace-card-mod) tools.

Something like this would work:
```yaml
    - type: custom:mini-thermostat
      entity: climate.my_thermostat
      style: |
        :host {
          --ha-card-header-font-size: 10px;
        }
        :host .card-header {
          line-height: 10px;
        }
        :host mwc-button {
          padding-top: 2px;
          padding-bottom: 2px;
        }
      name: Tiny header
```
