### ISSUE TITLE
Add service call example to README

### ISSUE THREAD

**Issue by artkrz** [Devqon/lovelace-mini-thermostat#18]
Please add an example of service call in the readme. There are examples for setting hvac mode but not for service, script call.

**Comment by Devqon** [comment]
See README:

```yaml
- type: custom:mini-thermostat
  entity: climate.main_thermostat
  layout:
    preset_buttons:
      - type: service
        entity: scene.turn_on
        label: Hot
        data:
          entity_id: scene.make_it_melting
```
