### ISSUE TITLE
Support for tap_action and hold_action

### ISSUE THREAD

**Issue by martinhoess** [Devqon/lovelace-mini-thermostat#8]
Would be nice if you could add the support for tap_action and hold_action (e.g. [Entity Button Card](https://www.home-assistant.io/lovelace/entity-button/))

Tried to do something like this:

```
type: 'custom:mini-thermostat'
entity: climate.netatmo_livingroom
layout:
  name: Heater
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    card:
      type: 'custom:simple-thermostat'
      entity: climate.netatmo_livingroom
      hold_action:
        action: none
      tap_action:
        action: none
      show_name: false
    title: Heater
```
